### ISSUE TITLE
How to convert FemToZip dictionary to Rhea dictionary

### ISSUE THREAD

**Issue by Geograph-us** [ayende/Rhea.Compression#3]
Is it possible use FemToZip-dictionaries in Rhea.Compression?

FemToZip header: 0x08000000 FemtoZip 0x00000000 0x00000100
Rhea header: 7bit_integer(1337) 7bit_integer(1) 7bit_integer(dictionary_len)

For standard FemtoZip 65536 length dictionary I try change original header to:
7bit_integer(1337) 7bit_integer(1) 7bit_integer(65536)
In HEX: 0xB90A01808004

but failed on Huffman-Tree loading

**Comment by ayende** [comment]
Very likely that this isn't going to work. This library was meant to learn how compression work and had a very specific goal in mind for doing so, it isn't a general / zip compression library.
